
schedule: "*/5 * * * *"

namespacesClean: "default"

releasesExclude:
  enabled: false

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podLabels:
  environment: "ci"
  test: "helm-chart"
