{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "release-cleaner.fullname" . }}
  labels:
    {{- include "release-cleaner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "release-cleaner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "release-cleaner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
